version: '3.8'
services:
  db:
    image: mariadb:10.6.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - dbvolume:/var/lib/mysql/data
    # Mac(M1)を使用している場合、platformに関するエラーが発生する可能性がある。エラー発生してから追加するのも良し。
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD  #=== .envの環境変数から持ってくる
    ports:
      - '3309:3309'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:  #=== Dockerfileに引数として渡せる
        WORKDIR: $WORKDIR
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/$WORKDIR
      - gem-store:/usr/local/bundle
    environment:  #=== 環境変数の設定
      TZ: Asia/Tokyo
      RAILS_ENV: development
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    depends_on:
      - db
    stdin_open: true
    tty: true
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        WORKDIR: $WORKDIR
    volumes:
      - ./frontend:/$WORKDIR:cached
      - node_modules:/$WORKDIR/node_modules
    ports:
      - '5173:5173'
    depends_on:
      - backend
    tty: true
    command: yarn dev --host
volumes:
  dbvolume:
  gem-store:
  node_modules: