databases:
  - name: coffee
    databaseName: coffee_production
    user: coffee_production_user
    plan: free

services:
  - type: web
    name: coffee_backend
    env: docker
    region: singapore
    branch: main
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: coffee_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default